version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shared-network
    volumes:
      - mongodb_data:/data/db

  auth-service:
    build:
      context: ./Auth
    container_name: auth-service
    ports:
      - "3183:3183"
    networks:
      - shared-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ClassroomMS

  classroom-service:
    build:
      context: ./Classrooms
    container_name: classroom-service
    ports:
      - "3184:3184"
    networks:
      - shared-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ClassroomMS

  post-service:
    build:
      context: ./Post
    container_name: post-service
    ports:
      - "3185:3185"
    networks:
      - shared-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ClassroomMS

  event-bus:
    build:
      context: ./event-bus
    container_name: event-bus
    ports:
      - "3186:3186"
    networks:
      - shared-network

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "1183:1183"
    networks:
      - shared-network
    depends_on:
      - auth-service
      - classroom-service
      - post-service
      - event-bus

networks:
  shared-network:
    driver: bridge

volumes:
  mongodb_data: