apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-1183
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/client:${BUILD_NUMBER}
        ports:
        - containerPort: 1183
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 1183
    targetPort: 1183
  type: LoadBalancer
